

version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    working_directory: ~/gather_fe
    docker:
      - image: cimg/ruby:2.7.4-node
        environment:
          PGHOST: localhost
          PGUSER: gather_fe
          RAILS_ENV: test
      - image: postgres:13.2
        environment:
          POSTGRES_USER: gather_fe
          POSTGRES_DB: gather_fe_test
          POSTGRES_PASSWORD:
    steps:
      - checkout
      - run:
          name: gather_fe
          command: bundle -v
      - ruby/bundle-install

      - checkout
      - run: bundle install --path vendor/bundle
      - run: bundle exec rspec